### ISSUE TITLE
UI Improvement 

### ISSUE THREAD

**Issue by AndrickSilva** [zetabug/rock-paper-scissors-game#15]
Hi, Listing a few changes that the improve the UI/UX
- I would like to remove the scroll
- You won page page after a best of 3 rounds.

Assign me this issue for the above changes
Thanks 

#hacktoberfest

**Comment by driptanil** [comment]
This project of yours is amazing, I had a lot of playing rock paper scissors, 

This is an animated gradient with moves from left to right, and I have solved the issue

![image](https://github.com/zetabug/rock-paper-scissors-game/assets/53353462/6d2558fc-293e-4e0c-a61d-67e9e32b6d37)

Please assign me this issue, and add hacktoberfest, and hacktoberfest-accepted labels.

After that, I would create a pull-request to your repository
