### ISSUE TITLE
Add reset button for score counters.

### ISSUE THREAD

**Issue by zetabug** [zetabug/rock-paper-scissors-game#4]

**Comment by Ishikasaraf20** [comment]
hey @zetabug can you assign this issue to i can work on it

**Comment by zainbinfurqan** [comment]
@zetabug can i work on it please

**Comment by zetabug** [comment]
Ok @zainbinfurqan

**Comment by KanjiZain** [comment]
Assign it to me if not completed !

**Comment by zetabug** [comment]
> Assign it to me if not completed !

get on it

**Comment by iamrahul25** [comment]
Hey, can you assign this issue to me!
